version: 2.1

workspace: &workspace
  ~/plugin-rtc

node-defaults: &node-defaults
  working_directory: *workspace
  executor:
    name: node/default
    tag: 13.10.1

release-filter: &release-filter
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    <<: *node-defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test -- -i --verbose

  publish-release:
    <<: *node-defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "publishing!"

workflows:
    build-and-test:
      jobs:
        - build-and-test

    publish-release:
      jobs:
        - build-and-test:
            <<: *release-filter
        - publish-release:
            <<: *release-filter
            requires: 
              - build-and-test